export const categories = [
  {
    title: 'Popular Books and Bestsellers',
    images: [
      '/assets/Images/Shop Examples/Popular Books and Bestsellers/Popular_Books_1.png',
      '/assets/Images/Shop Examples/Popular Books and Bestsellers/Popular_Books_2.png',
      '/assets/Images/Shop Examples/Popular Books and Bestsellers/Popular_Books_3.png',
      '/assets/Images/Shop Examples/Popular Books and Bestsellers/Popular_Books_4.png',
      '/assets/Images/Shop Examples/Popular Books and Bestsellers/Popular_Books_5.png',
      '/assets/Images/Shop Examples/Popular Books and Bestsellers/Popular_Books_6.png',
      // Image 7 is missing, so leave as empty string to trigger fallback
      '',
      '/assets/Images/Shop Examples/Popular Books and Bestsellers/Popular_Books_8.png',
    ],
    author: 'Alex Chen',
    summaries: [
      'A gripping tale of mystery and intrigue that keeps readers on the edge of their seats.',
      'An inspiring story of personal growth and overcoming adversity in modern society.',
      'A heartwarming romance that explores the depths of love and human connection.',
      'A thrilling adventure across uncharted territories filled with danger and discovery.',
      'A thought-provoking narrative about identity and self-discovery in a changing world.',
      'A suspenseful crime story that unravels secrets from the past.',
      'An epic journey of friendship and loyalty tested by extraordinary circumstances.',
      'A compelling drama about ambition, success, and the cost of dreams.',
    ],
  },
  {
    title: 'Superhero Comics',
    images: [
      '/assets/Images/Shop Examples/Superhero/Superhero_1.png',
      '/assets/Images/Shop Examples/Superhero/Superhero_2.png',
      '/assets/Images/Shop Examples/Superhero/Superhero_3.png',
      '/assets/Images/Shop Examples/Superhero/Superhero_4.png',
      '/assets/Images/Shop Examples/Superhero/Superhero_5.png',
      '/assets/Images/Shop Examples/Superhero/Superhero_6.png',
      '/assets/Images/Shop Examples/Superhero/Superhero_7.png',
      '/assets/Images/Shop Examples/Superhero/Superhero_8.png',
    ],
    author: 'Stan Jackson',
    summaries: [
      'Captain America faces his greatest challenge yet as reality itself begins to unravel.',
      'The Flash races against time to prevent a catastrophic timeline collapse.',
      'Iron Man battles advanced AI threats that could end humanity.',
      'Spider-Man discovers a new villain with powers beyond comprehension.',
      'Wonder Woman leads an alliance against an ancient evil awakening.',
      'Batman confronts his darkest fears in a city under siege.',
      'Superman struggles with the limits of his power against cosmic foes.',
      'The Avengers unite for a final stand against ultimate destruction.',
    ],
  },
  {
    title: 'Fantasy Adventures',
    images: [
      '/assets/Images/Shop Examples/Fantasy/Fantasy_1.png',
      '/assets/Images/Shop Examples/Fantasy/Fantasy_2.png',
      '/assets/Images/Shop Examples/Fantasy/Fantasy_3.png',
      '/assets/Images/Shop Examples/Fantasy/Fantasy_4.png',
      '/assets/Images/Shop Examples/Fantasy/Fantasy_5.png',
      '/assets/Images/Shop Examples/Fantasy/Fantasy_6.png',
      '/assets/Images/Shop Examples/Fantasy/Fantasy_7.png',
      '/assets/Images/Shop Examples/Fantasy/Fantasy_8.png',
    ],
    author: 'Eleanor Blackwood',
    summaries: [
      'A young wizard discovers ancient magic that could save or destroy the realm.',
      'Elves and dragons clash in an epic battle for the fate of Middle-earth.',
      'A quest for the lost crown leads through enchanted forests and dark dungeons.',
      'Mages harness forbidden spells to combat rising darkness.',
      'A prophecy unfolds as heroes from different worlds unite.',
      'Mythical creatures guard secrets that could change history.',
      'A sorceress battles demons from another dimension.',
      'Knights embark on a perilous journey to find the ultimate artifact.',
    ],
  },
  {
    title: 'Science Fiction',
    images: [
      '/assets/Images/Shop Examples/Science Fiction/Science_Fiction_1.png',
      '/assets/Images/Shop Examples/Science Fiction/Science_Fiction_2.png',
      '/assets/Images/Shop Examples/Science Fiction/Science_Fiction_3.png',
      '/assets/Images/Shop Examples/Science Fiction/Science_Fiction_4.png',
      '/assets/Images/Shop Examples/Science Fiction/Science_Fiction_5.png',
      '/assets/Images/Shop Examples/Science Fiction/Science_Fiction_6.png',
      '/assets/Images/Shop Examples/Science Fiction/Science_Fiction_7.png',
      '/assets/Images/Shop Examples/Science Fiction/Science_Fiction_8.png',
    ],
    author: 'Isaac Sterling',
    summaries: [
      'Astronauts discover alien life on a distant planet with shocking implications.',
      'Time travelers alter history to prevent a global catastrophe.',
      'AI becomes sentient and questions its purpose in human society.',
      'Colonists on Mars face unknown threats from the red planet.',
      'A scientist creates a device that can predict the future.',
      'Space explorers encounter a civilization from another galaxy.',
      'Virtual reality worlds become indistinguishable from reality.',
      'Genetic engineering leads to superhuman abilities and ethical dilemmas.',
    ],
  },
]